## DATABASEDOTCOM -- SALESFORCE
CLIENT_SECRET: '9064557118446309377'
CLIENT_ID: 3MVG9fMtCkV6eLhf7hFFI0RoP_KikoEAFElVZNB_2uxfaHim5VBp5fzrVkInsQNJI_MgoWn4VR1L41FSeqgVK
USERNAME: 'rfp@gasvaluation.com'
PASSWORD: 'Jaytory7'
# SECURITY_TOKEN: McWhiPmmvaoB0bLqgnkKtb8vz
API_VERSION: '35.0'

development:
  G_ID: 971068301360-3aqmuu7otoao9fcnvdo4jneis0vvqnfb.apps.googleusercontent.com
  G_SECRET: Ha4egQD8f1HMaNODhiSbwvlv
  GMAIL_USERNAME: erikbatres@gmail.com
  GMAIL_PASSWORD: tpvnnlcduvmmikhq
  G_MAP_SERVER_KEY: AIzaSyC8fQd_amXThhlLzQIRYRAEKtwKvqSKcr0
  FLOWDOCK_API_KEY: e14fe997356295f07f008914743712a1
  NYTIMES_MOST_POPULAR: 0bbfe58a213dd9658f74d99a11f425a6:5:73801478
  NYTIMES_TOP_STORIES: 2b3fda02ff0e916e5f479c34813515f6:6:73801478

test:
  G_MAP_SERVER_KEY: AIzaSyC8fQd_amXThhlLzQIRYRAEKtwKvqSKcr0
  NYTIMES_MOST_POPULAR: 0bbfe58a213dd9658f74d99a11f425a6:5:73801478
  NYTIMES_TOP_STORIES: 2b3fda02ff0e916e5f479c34813515f6:6:73801478

production:
  G_ID: 187745245612-06efpf3a46p44ni2v93vi3hcm8qokab8.apps.googleusercontent.com
  G_SECRET: BYR32KJTuIkhFaBai9Krg_yQ
  FLOWDOCK_API_KEY: e14fe997356295f07f008914743712a1
  G_MAP_SERVER_KEY: AIzaSyBpV3kvh-4G8R2P7jx4_TLAuSZr4xV-MJU
  NYTIMES_MOST_POPULAR: 0bbfe58a213dd9658f74d99a11f425a6:5:73801478
  NYTIMES_TOP_STORIES: 2b3fda02ff0e916e5f479c34813515f6:6:73801478